
version: 0.2

phases:
  install:
    commands:
     #- sudo apt-get update
     #- sudo curl -fsSL https://get.docker.com -o get-docker.sh # to download docker if needed
     #- sudo sh get-docker.sh
     #- sudo service --status-all # to see if docker is running, it should be
      - docker pull checkmarx/dast:latest #pull the latest docker dast image
      
  build:
    commands:
      - pwd 
     #- uname -a
      - ls
     #- whoami
     #- cat gin_juice.yaml
     #- chmod 777 gin_juice.yaml
      - docker run -e CX_APIKEY='${{ secrets.CX_DEU_API_KEY }}' -v $(pwd):/dast_home checkmarx/dast:latest web --environment-id='7d57e5e8-69ec-42b9-882b-1f56172742da' --config='/dast_home/gin_juice.yaml' --base-url=https://deu.ast.checkmarx.net/ --output='/dast_home/DAST_results/dast_scan_output' --jvm-properties=-Xmx3G --log-level=trace --verbose --retry=3 --retry-delay=20
           
artifacts:
  files:
    - '**/*'
  # - 'Gin_juice.yaml'
    - '/dast_home/DAST_results/dast_scan_output'
