
version: 0.2

phases:
  install:
    commands:
     # - sudo apt-get update
     # - sudo curl -fsSL https://get.docker.com -o get-docker.sh
     # - sudo sh get-docker.sh
     # - sudo service --status-all
      - docker pull checkmarx/dast:latest
      
  build:
    commands:
      - docker run -e CX_APIKEY=$API_KEY \
          -v $(pwd):/demo checkmarx/dast:latest \
          web \
          --environment-id=7d57e5e8-69ec-42b9-882b-1f56172742da \
          --config=./gin_juice.yaml \
          --base-url=https://deu.ast.checkmarx.net/ \
          --output=/demo/test_output \
          --timeout=10000 \
          --update-interval=10 \
          --jvm-properties=-Xmx3G \
          --log-level=info \
          --verbose \
          --retry=3 \
          --retry-delay=20 \
          --fail-on HIGH
          
artifacts:
  files:
    - '**/*'
