
version: 0.2

phases:
  install:
    commands:
     #- sudo apt-get update
     #- sudo curl -fsSL https://get.docker.com -o get-docker.sh # to download docker if needed
     #- sudo sh get-docker.sh
     #- sudo service --status-all # to see if docker is running, it should be
      - docker pull checkmarx/dast:latest #pull the latest docker dast image
      
  build:
    commands:
      - pwd 
     #- uname -a
      - ls
     #- whoami
     #- cat gin_juice.yaml
     #- chmod 777 gin_juice.yaml
      - docker run -e CX_APIKEY='eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhODZiNjEzNC0xZGMwLTRjMjktODIyYi0zZDhhYmRjYzg1NTYifQ.eyJpYXQiOjE2ODk2MDI1ODgsImp0aSI6IjNhYjNjOWU4LTBmYmMtNGFmZi1iNjU1LTUxYTczMTdkNjgwMiIsImlzcyI6Imh0dHBzOi8vZGV1LmlhbS5jaGVja21hcngubmV0L2F1dGgvcmVhbG1zL2NoZWNrbWFyeC1nbG9iYWwtc2VydmljZXMtaW50ZXJuYWwiLCJhdWQiOiJodHRwczovL2RldS5pYW0uY2hlY2ttYXJ4Lm5ldC9hdXRoL3JlYWxtcy9jaGVja21hcngtZ2xvYmFsLXNlcnZpY2VzLWludGVybmFsIiwic3ViIjoiYzJkZTMxZDctZTUwMS00Njk2LTlhNjAtMWY1YmJiYzAxMTk5IiwidHlwIjoiT2ZmbGluZSIsImF6cCI6ImFzdC1hcHAiLCJzZXNzaW9uX3N0YXRlIjoiYzI3ZjE4MjgtNzM4ZS00ZWEyLTgzNTYtMjg3OTE4YmFmYWY4Iiwic2NvcGUiOiIgb2ZmbGluZV9hY2Nlc3MiLCJzaWQiOiJjMjdmMTgyOC03MzhlLTRlYTItODM1Ni0yODc5MThiYWZhZjgifQ.obnKd5oDWbTi5aYz3OjSlZSHwFpHWkRPx2AVNbpHwqc' -v $(pwd):/dast_home checkmarx/dast:latest web --environment-id='7d57e5e8-69ec-42b9-882b-1f56172742da' --config='/dast_home/7.17test2_gin_juice.yaml' --base-url=https://deu.ast.checkmarx.net/ --output='/dast_home/DAST_results/dast_scan_output' --jvm-properties=-Xmx3G --log-level=trace --verbose --retry=3 --retry-delay=20
           
artifacts:
  files:
    - '**/*'
  # - 'Gin_juice.yaml'
    - '/dast_home/DAST_results/dast_scan_output'
