---
env:
  contexts:
    - name: "GinAndJuice"
      urls:
        - "https://ginandjuice.shop"
      includePaths:
        - "https://www.ginnjuice.shop/listing/boobs-are-bullshit?product=46/.*"
      excludePaths: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
  - parameters:
      maxAlertsPerRule: 0
      scanOnlyInScope: true
      maxBodySizeInBytesToScan: 0
      enableTags: false
    rules: []
    name: "passiveScan-config"
    type: "passiveScan-config"
  - parameters:
      context: "GinAndJuice"
      user: ""
      url: "https://ginandjuice.shop/"
      maxDuration: 10
      maxDepth: 0
      maxChildren: 0
      acceptCookies: false
      handleODataParametersVisited: false
      handleParameters: "IGNORE_COMPLETELY"
      maxParseSizeBytes: 0
      parseComments: false
      parseGit: false
      parseRobotsTxt: false
      parseSitemapXml: false
      parseSVNEntries: false
      postForm: false
      processForm: false
      requestWaitTime: 0
      sendRefererHeader: false
      userAgent: ""
    name: "spider"
    type: "spider"
  - parameters:
      context: "GinAndJuice"
      user: ""
      url: "https://ginandjuice.shop/"
      maxDuration: 10
      maxCrawlDepth: 3
      numberOfBrowsers: 16
      runOnlyIfModern: false
    name: "spiderAjax"
    type: "spiderAjax"
  - parameters: {}
    name: "passiveScan-wait"
    type: "passiveScan-wait"
  - parameters:
      context: "GinAndJuice"
      user: ""
      policy: ""
      maxRuleDurationInMins: 0
      maxScanDurationInMins: 0
      addQueryParam: false
      delayInMs: 0
      handleAntiCSRFTokens: false
      injectPluginIdInHeader: false
      scanHeadersAllRequests: false
      threadPerHost: 5
    policyDefinition:
      defaultStrength: "medium"
      defaultThreshold: "medium"
      rules: []
    name: "activeScan"
    type: "activeScan"
  - parameters:
      template: "risk-confidence-html"
      reportDir: "C:\\Users\\joaor"
      reportTitle: "ZAP Scanning Report"
      reportDescription: ""
    name: "report"
    type: "report"
