# ************************************* CHECKMARX CONFIGURATION FILE **********************************************
# * To use this file as 'Config as code' you need to save it under a specific location in your source directory:  *
# * Under your root, create a folder: ".checkmarx"                                                                *
# * In this new folder place this file, and rename it to: "config.yml"                                            *
# *****************************************************************************************************************

version: 1

# checkmarx-specific related configuration
# every value in this section is optional 
checkmarx: 
  # configure the checkmarx scan parameters for scanning this specific project
  scan:
    # scan tags. can be in a key-value format OR "label" format where the value is an empty string.
    tags:
      # example: "priority": "high"
      # example: "test": ""

    # configure the checkmarx scan configurations for scanning this specific project
    configs:
      # configure the SAST related configurations this specific project
      sast:
        # configure the SAST preset name used for this specific project
        presetName: 'Checkmarx Default'
         # configure if this specific project will be run incrementally or will it run a full scan 
        incremental: 'false'
