# This is a basic workflow to help you get started with Actions

name: CxAST CLI Action - Scan on Pull

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches:
    - main
    - master
    - release/*
    
  schedule:
  - cron: "0 2 * * 1-5"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST Github Action
        # You may pin to the exact commit or the version.
        # uses: Checkmarx/ast-github-action@0fcee7e03446692b38464ac6ec3a47bf1deb1c27
        uses: Checkmarx/ast-github-action@2.0.9
        with:
          base_uri: https://ast.checkmarx.net/
          cx_tenant: ${{ secrets.TENANT }} 
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
          #project_name:
          # optional, default is ${{ github.repository }}
          #branch:
          # optional, default is ${{ github.head_ref || github.ref }}
          # GitHub API Token
          github_token: ${{ secrets.GHTOKEN }}
          # optional, default is ${{ github.token }}
          # Additional parameters for AST scan
          additional_params: --threshold sast-high=200 --file-filter !readme --report-format sarif --output-name CX
          #--sast-filter !src/main/webapp
          #repo_name:
          # optional, default is ${{ github.event.repository.name }}
          # Organization name to create the Pr comment
          #namespace:
          # optional, default is ${{ github.repository_owner }}
          # Pr Number of the pull request that needs the decoration
          #pr_number:
          # optional, default is ${{ github.event.number }}
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: CX.sarif
