name: CxAST CLI Action - Scan on Push
on:
  push:
     branches:
     - main
     - master
     - release/*
    
  schedule:
  - cron: "0 2 * * 1"
  
  workflow_dispatch: # This is a basic workflow to help you get started with Actions
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Checkmarx AST Github Action
        # You may pin to the exact commit or the version.
        # uses: Checkmarx/ast-github-action@0fcee7e03446692b38464ac6ec3a47bf1deb1c27
        uses: Checkmarx/ast-github-action@2.0.9
        with:
          base_uri: ${{ secrets.BASE_URI }}
          cx_tenant: ${{ secrets.TENANT }} 
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
          #project_name: optional, default is ${{ github.repository }}
          #branch: optional, default is ${{ github.head_ref || github.ref }}
          github_token: ${{ secrets.GHTOKEN }} # GitHub API Token
          # optional, default is ${{ github.token }}
          # Additional parameters for AST scan
          additional_params: --threshold sast-high=200 --report-format sarif --output-name cxResults --output-path . --scan-types sast,sca,iac-security
          #--sast-filter !src/main/webapp --file-filter !readme
          #repo_name:
          # optional, default is ${{ github.event.repository.name }}
          # Organization name to create the Pr comment
          #namespace:
          # optional, default is ${{ github.repository_owner }}
          # Pr Number of the pull request that needs the decoration
          #pr_number:
          # optional, default is ${{ github.event.number }}
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cxResults.sarif
