# This is a basic workflow to help you get started with Actions

name: CxONE Scan on PR/Push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches:
    - main
    - master
    - release/*
    - dev/*
  push:
    branches:
    - main
    - master
    - release/*
    - dev/*
    
  schedule:
  - cron: "0 2 * * 5"

  workflow_dispatch:
     inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Cx Tags'
        required: false
        type: string
      print_tags:
        description: 'True to print to STDOUT'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
permissions: 
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
        #############
      - name: Checkout
        uses: actions/checkout@v3
        #############
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@main
        with:
          base_uri: https://ast.checkmarx.net/
          cx_tenant: ${{ secrets.TENANT }} 
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
          namespace: ${{ github.repository_owner }}
          github_token: ${{ secrets.GHTOKEN }}
          pr_number: ${{ github.event.number }}
          additional_params: --threshold sast-high=200 --report-format sarif --output-name cxResults --sast-filter !src/main/webapp --file-filter !readme
          ##############
          #project_name:
          # optional, default is ${{ github.repository }}
          #branch:
          # optional, default is ${{ github.head_ref || github.ref }}
          #repo_name:
          # optional, default is ${{ github.event.repository.name }}
          #############
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cxResults.sarif
