---

---
name: CxONE Scan on PR
on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches-ignore:

    
  schedule:


  workflow_dispatch:


# This cancels in progress job if another workflow is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
  - name: ZAP Scan
    uses: zaproxy/action-baseline@v0.9.0
    with:
      target: 'Https://www.ast.checkmarx.net'
